version: "3.3"
services:
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./config_docker/backend.dockerfile
        env_file: production.env
        command: ./dist/b-main/index.js
        ports:
            - 3000:3000
        networks:
            - pp
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.backend_stripprefix.stripprefix.prefixes=/api"
            - "traefik.http.routers.backend.middlewares=backend_stripprefix"
            - "traefik.http.routers.backend.rule=Host(`pp.kleselcodes.de`) && PathPrefix(`/api`)"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls.certresolver=myresolver"
            - "traefik.http.services.backend.loadbalancer.server.port=3000"

    game-ui:
        restart: always
        build:
            context: .
            dockerfile: ./config_docker/dashboard.ui.dockerfile
        env_file: game.production.env
        networks:
            - proxy
        expose:
            - "80"
        depends_on:
            - backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.game-ui.rule=Host(`pp.kleselcodes.de`)"
            - "traefik.http.routers.game-ui.entrypoints=websecure"
            - "traefik.http.routers.game-ui.tls.certresolver=myresolver"

networks:
    pp:
    proxy:
        external: true
        name: "traefik_proxy"
