version: "3.3"
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5434:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: fcv2
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    minodata:
    pgdata:
