version: "3.3"
services:
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./config_docker/backend.dockerfile
        env_file: production.env
        command: ./dist/b-main/index.js
        ports:
            - 3000:3000

    game-ui:
        restart: always
        build:
            context: .
            dockerfile: ./config_docker/dashboard.ui.dockerfile
        env_file: game.production.env
        ports:
            - 3001:80
        depends_on:
            - backend
