version: "3.3"
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fcv2
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  mino:
    image: minio/minio
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minodata:/export
    command: server /data

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
    
volumes:
  minodata:
  pgdata:
