name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Runs a set of commands using the runners shell
            - name: backend
              run: |
                  docker build -t pp/backend -f ./config_docker/backend.dockerfile .
                  docker tag pp/backend:latest ghcr.io/tobi12345/pp/backend:latest
                  docker push ghcr.io/tobi12345/pp/backend:latest

            # Runs a set of commands using the runners shell
            - name: ui
              run: |
                  docker build -t pp/ui -f ./config_docker/dashboard.ui.dockerfile .
                  docker tag pp/ui:latest ghcr.io/tobi12345/pp/ui:latest
                  docker push ghcr.io/tobi12345/pp/ui:latest
